<?php echo $block->escapeUrl($block->getUrl('bookgrocery/index/save')) ?>
<!-- <?= $block->escapeUrl($block->getAction()) ?> -->
<form id="bookgrocery-form" method="post" action="<?php echo $block->escapeUrl($block->getUrl('bookgrocery/index/save')) ?>" enctype="multipart/form-data" data-mage-init='{"validation":{}}'>
    <div class="field name required">
        <label for="name" class="label"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
        <div class="control">
            <input type="text" name="name" id="name" title="<?= $block->escapeHtmlAttr(__('Name')) ?>" class="input-text" data-validate="{required:true}" placeholder="<?= $block->escapeHtml(__('Your name')) ?>">
        </div>
    </div>
    <div class="field email required">
        <label for="email" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
        <div class="control">
            <input type="email" name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="input-text" data-validate="{required:true, 'validate-email':true}" placeholder="<?= $block->escapeHtml(__('Your email address')) ?>">
        </div>
    </div>
    <div class="field phone required">
        <label for="phone" class="label"><span><?= $block->escapeHtml(__('Phone')) ?></span></label>
        <div class="control">
            <input type="text" name="phone" id="phone" title="<?= $block->escapeHtmlAttr(__('Phone')) ?>" class="input-text" data-validate="{required:true}" placeholder="<?= $block->escapeHtml(__('Your phone number')) ?>">
        </div>
    </div>
    <div class="field products required">
        <label for="products" class="label"><span><?= $block->escapeHtml(__('Products')) ?></span></label>
        <div class="control">
            <textarea name="products" id="products" title="<?= $block->escapeHtmlAttr(__('Products')) ?>" class="input-text" placeholder="<?= $block->escapeHtml(__('Please list the products you would like to order')) ?>"></textarea>
        </div>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary" title="<?= $block->escapeHtmlAttr(__('Book Grocery')) ?>"><span><?= $block->escapeHtml(__('Book Grocery')) ?></span></button>
        </div>
    </div>
    <?= $block->getBlockHtml('formkey') ?>
</form>
